feat: add autohide after inactivity
Infiziert90/ChatTwo pull request #83
Opened 2024-07-11 06:00 UTC by deansheather

After not receiving a message for X seconds (configurable) in the current tab or any tab with unread mode enabled, the chat will be hidden. Focus can be returned with return or slash as usual.

Having input focus or hovering the mouse over the chat window "bumps" it every frame.

Also fixes a bug that prevented focus from being restored to tabs with input disabled. The chat window will now be correctly brought back but the activated event won't be fully processed.

Thanks @aurieh

https://github.com/Infiziert90/ChatTwo/assets/11241812/5a2b4f8a-99e6-4a67-8ae8-b154b7cab9a6

Relates to #80

2024-07-11 13:35 UTC, ethanndickson approved these changes

2024-07-12 15:49 UTC, Infiziert90 requested changes

2024-07-12 15:49 UTC, Infiziert90 commented on ChatTwo/Ui/ChatLogWindow.cs
> +        var lastActivityTime = Plugin.Config.Tabs
Max() could throw if the Where is empty for some reason

2024-07-12 15:49 UTC, Infiziert90 commented on ChatTwo/Ui/SettingsTabs/Display.cs
> +            if (Mutable.InactivityHideTimeout < 2)
Use Math.Clamp or Math.Min, is cleaner

2024-07-13 07:30 UTC, merged